name: hexo-deploy

on:
  push:
    branches:
      - posts

  workflow_dispatch:

jobs:
  hexo-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm install hexo-cli
          npm install
          git read-tree --prefix=source/_posts/ -u origin/posts
          npx hexo clean
          npx hexo generate
          git add public
          git commit -m "hexo deploy"
          git checkout gh-pages
          git read-tree --reset -u main:public/
          git commit -m "hexo deploy"
          git push origin gh-pages